# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install tensorflow
        pip install flake8
        pip install -r requirements.txt
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
    - name: Download Model
      run: |
        mkdir -p saved_models
        curl -L -o "saved_models/my_model_eff.keras" "https://github.com/ShreyasChakravarthy19/FoodDetectionandCalorieEstimation/releases/download/v1.0/my_model_eff.keras"
      shell: bash

    - name: Verify Model File
      run: |
        if [ ! -s "saved_models/my_model_eff.keras" ]; then
          echo "Model file not found or is empty!"
          exit 1
        fi
      shell: bash
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
